### ISSUE TITLE
ext/data/logs/debugs.log is too large

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#100]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

There is a situation where ext/data/logs/debugs.log is too large, reaching up to 270GB. May I ask how to solve this.

### Expected Behavior

I want to close this log

### Steps To Reproduce

Everything else is normal, except for this file which is too large

### Operating System

Windows

**Comment by shdwmtr** [comment]
What does the file contain? Because the logs Millennium should be producing are bytes/kilobytes. That's insanely large

**Comment by YCZ01111** [comment]
> What does the file contain? Because the logs Millennium should be producing are bytes/kilobytes. That's insanely large

I am not sure what is included in the document. Because this didn't happen on my computer. The only feedback I received was this screenshot.
![0D9C0E36E5B8A4A1E731A6586C1F425D](https://github.com/user-attachments/assets/ff9fd9fc-b7c6-4fbd-ae94-3698aaae8f67)

**Comment by YCZ01111** [comment]
So can he close this log?

**Comment by shdwmtr** [comment]
He can delete it yes, It's not important.

**Comment by shdwmtr** [comment]
I'm adding some safe guards in the new version of Millennium to prevent this.

**Comment by YCZ01111** [comment]
> I'm adding some safe guards in the new version of Millennium to prevent this.

Okay, thank you for your response.
