### ISSUE TITLE
[Bug] Themes not showing in the dropdown menu, and got an error in console running -dev flag.

### ISSUE THREAD

**Issue by ejrv** [SteamClientHomebrew/Millennium#104]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

So I ran Steam with the -dev flag and it gave this error:
![image](https://github.com/user-attachments/assets/467205ba-115a-4dc1-a200-bb3bb2cc6cf2)
And also there is no option in the interface for Open Millennium or anything related to millennium.
![{8FCE3BC9-2E06-45C1-AD47-793017950542}](https://github.com/user-attachments/assets/33873183-29d6-4342-8421-3693a94ef867)

I've tried applying a theme but got nothing in the dropdown menu:
![image](https://github.com/user-attachments/assets/04380a50-1cec-4deb-89b0-c96ee543b2bc)
This is what my skins folder looks like:
![image](https://github.com/user-attachments/assets/62f98b1c-7569-472a-972b-b24fc2721148)
And the files inside of one of those folders:
![{DC11BC0D-5363-4F7F-A63D-3F1622F4BAAF}](https://github.com/user-attachments/assets/40893fe9-084c-48d5-a009-3256cfba7f91)

### Expected Behavior

Possibility to enable themes and get no error in console.

### Steps To Reproduce

I did both automatic and manual installation but the problem still exists.

### Operating System

Windows

### Anything else?

Tried with the old windows theme and 2013&2015 classic steam but none got shown in the dropdown menu.

**Comment by nubnub4455** [comment]
in regards to the dropdown menu, just confirmed that this is just an issue with that individual skin, as installing any other skin will show it in the dropdown menu.
![image_2024-09-14_030351499](https://github.com/user-attachments/assets/49aefea9-94de-48ea-8bf7-694ddb6ab6da)

**Comment by ricewind012** [comment]
> in regards to the dropdown menu, just confirmed that this is just an issue with that individual skin, as installing any other skin will show it in the dropdown menu.

it's not, it should look like this
![image](https://github.com/user-attachments/assets/2d2b8549-6e48-4bd1-8249-0bd62a80d54f)
download it from [here](https://codeload.github.com/eyedine2/Classic-Steam-Library/zip/refs/heads/main) and put the folder in the archive in the "skin" folder

**Comment by lucipher** [comment]
Having the same issue with Fluent For Steam 0.4.4.2fix (https://github.com/purogamer/Fluent-for-Steam/releases/tag/0.4.4.2fix). First time trying to install a theme, so don't know if I messed up :/

**Comment by shdwmtr** [comment]
@lucipher that theme no longer works.
