### ISSUE TITLE
[Bug]I entered and it uninstalled

### ISSUE THREAD

**Issue by Ilie-Ioan** [SteamClientHomebrew/Millennium#105]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

Hello.When i enter today on steam i saw the theme wasnt on and the other features werent there.When i put again the command on installing and it was back to normal

### Expected Behavior

How to remain the theme

### Steps To Reproduce

1 open steam
2 i see not the team
3 open power shell and put the installing command even thought was installed 
4 workin now

### Operating System

Windows

**Comment by Ilie-Ioan** [comment]
and now it crashed

**Comment by shdwmtr** [comment]
Most likely your anti-virus interfering with Millennium.

**Comment by Ilie-Ioan** [comment]
> Most likely your anti-virus interfering with Millennium.

I have microsoft antivirus

**Comment by shdwmtr** [comment]
Yeah that's fine, but you need to whitelist your entire Steam folder. `C:\Program Files (x86)\Steam`
