### ISSUE TITLE
about webkit.css

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#106]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

Firstly, I set it up in the libraryloot. custom. css file
._3mz8wQ6Q44B8P7pzPP4Iyw {
background-image: url("main.jpg");
background-position: center;
background-size: cover;
}

and in the webkit.css file 

body {
background: rgba(0, 0, 0, 0.5) ! important;
}

On a very small number of computers, the background color of the store is not transparent.
<img width="640" alt="99302f84e1faee10e2889b0d49a0c34c_720" src="https://github.com/user-attachments/assets/9491515a-8204-4453-9db6-21a6d170dd3e">

I have tried "background: transparent ! important;" but it did not work, too

Is there a theme creator who can solve this problem.

### Expected Behavior

![image](https://github.com/user-attachments/assets/25a9728d-9b86-4e26-91bd-d9fae0473278)

### Steps To Reproduce

body {
background: rgba(0, 0, 0, 0.5) ! important;
}

### Operating System

Windows

### Anything else?

Sorry, I have to check the above options because https://github.com/SteamClientHomebrew/Core non-existent

**Comment by shdwmtr** [comment]
Unfortunately you just can't rely on it being transparent. Its a Steam issue, not something with Millennium. I still don't know exactly what causes it.

I am making a plugin *soon* (absolutely no ETA) that will force all windows to be transparent.
