### ISSUE TITLE
[Bug] Millennium not starting correctly on startup.

### ISSUE THREAD

**Issue by AsuToki360** [SteamClientHomebrew/Millennium#107]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

For some reason Millennium doesn't launch the way as it should. There's no options and the theme is only applied for some pages (like the Workshop or the Store) but not on the entire client.

When I close Steam entirely and open it again, it opens with my theme 100% applied and everything, strange...

### Expected Behavior

Steam launcing correctly with my theme applied.

### Steps To Reproduce

1. Boot my PC (or restart it)
2. Open Steam

### Operating System

Windows

**Comment by shdwmtr** [comment]
Does this happen when Steam is first launched? Or after letting your PC sleep or something.

**Comment by AsuToki360** [comment]
It happens when Steam is first launched when turning on the PC

**Comment by shdwmtr** [comment]
Try another theme, see if that fixes it.

**Comment by shdwmtr** [comment]
Closing for no response

**Comment by Trimint123** [comment]
> Try another theme, see if that fixes it.

I had the same issue. It just doesn't open on startup with Steam properly with custom themes in general. I tested with OldSteam and SpaceTheme.
