### ISSUE TITLE
[Bug]Steam Crashes When Opening DevTools from Add a Game Button

### ISSUE THREAD

**Issue by EugeneXXXie** [SteamClientHomebrew/Millennium#108]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

When I click this button and open DevTools, Steam crashes immediately.
This is the 'Add a Game' button at the bottom left of Steam window
![image](https://github.com/user-attachments/assets/142cbb52-b221-4118-94cc-7952beba80f2)

### Expected Behavior

I expected Steam to continue running without any issues when I open DevTools.

### Steps To Reproduce

1,Start Steam with Startup Items -cef-enable-debugging -dev.
2,Click this button.
3,Open DevTools. （F12）
4,Steam crashes immediately.

### Operating System

Windows

### Anything else?

![image](https://github.com/user-attachments/assets/c1e4682c-727f-4f92-8b3a-52956c972102)

**Comment by shdwmtr** [comment]
This isn't an issue with Millennium unfortunately. It happens on a clean install of Steam. You have to use other methods of skinning the window. You can go to http://localhost:8080 with Steam open, and you can edit windows there crash free.
