### ISSUE TITLE
[Bug] Steam UI freezes on plugin load/unload.

### ISSUE THREAD

**Issue by Plaer1** [SteamClientHomebrew/Millennium#110]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

![image](https://github.com/user-attachments/assets/e84ec152-6831-42f2-9508-3be720b44818)
this repo 404'd or I wouldn't post this here.

### Describe the Bug

Pretty much what it says on the tin, steam UI freezes, I don't see anything particularly alarming in the Mil console log either.

### Expected Behavior

The plugin should just enable or disable.

### Steps To Reproduce

1) download/compile example plugin
2) enable/disable plugin
(also works with other plugins)

### Operating System

Windows

**Comment by shdwmtr** [comment]
Thanks, fixed in 41209564158e3de86654cfdf4b2d6be2e200f155

**Comment by shdwmtr** [comment]
This is now 100% fixed, it will be released soon. I'll close this issue, but reopen it if you have issues!
