### ISSUE TITLE
[Feature] Theme path variable

### ISSUE THREAD

**Issue by Plaer1** [SteamClientHomebrew/Millennium#117]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

I already hard coded it in my skin, but it would probably be nice to have a path variable.

**Comment by shdwmtr** [comment]
Turns out this can't be easily done, and for what its worth, its not.
