### ISSUE TITLE
[Feature] Add version numbers to themes and plugins

### ISSUE THREAD

**Issue by Josh65-2201** [SteamClientHomebrew/Millennium#118]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

Right now it hard to tell what version of millennium or any theme I'm on since it not shown. This could be shown next to the name
Name - v2.0.0

**Comment by shdwmtr** [comment]
The version of a theme is available under the (i) icon in the themes panel. 
![{1586BD8F-99C5-4C91-A9E0-8349BA589508}](https://github.com/user-attachments/assets/51a046da-4934-4427-aaa3-b9b61e45946c)

You can see the version of Millennium by running
`millennium --version` in cmd/powershell

**Comment by Josh65-2201** [comment]
Since there's still no way of seeing plugin version installed and there's no `millennium.exe` now, can this be reopened for plugin version on the UI
