### ISSUE TITLE
[Bug] Millennium keeps resetting to default steam every boot

### ISSUE THREAD

**Issue by MrMAXVW** [SteamClientHomebrew/Millennium#121]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

Everytime I reboot my PC, the steam will reset to default.
There is no options from millennium can be seen.
I have to do the powershell script every time to bring back millennium and the theme.

What I have tried:
- Fresh reinstall steam
- Uninstall millennium and install again

My settings:
- Steam located in D:\Steam
- Using fluenty theme
- Millennium version 2.11.1

Is it steam forcing something? Or I should install specific version of steam.
But I don't think that's a problem.
I had 3 PC installed millenium with the same theme.
Only one pc has this problem... kinda frustrating

### Expected Behavior

As mentioned above

### Steps To Reproduce

Reboot > open steam > steam reset to default
**update: switching account make this happens too
A .crash file appears in steam folder

[GameOverlayRenderer.log](https://github.com/user-attachments/files/17246357/GameOverlayRenderer.log)

When I run the powershell script again, I see more lines shown in the picture
![2024-10-03 225209](https://github.com/user-attachments/assets/2a47e17b-7587-4b1e-bce7-c3f7bc7a6f78)

### Operating System

Windows

**Comment by shdwmtr** [comment]
When you notice it not working anymore do the following:

* Check you antivirus hasn't deleted Millennium.
* Check `user32.dll` exists in the Steam folder.

You can also start steam with `-dev` and leaving it running like that until either you see an error, or the dev console no longer shows.

**Comment by MrMAXVW** [comment]
Hi,
I took some more time to troubleshoot, the problem still exists
- tried changing other theme
- tried moving the steam folder from another pc to my laptop
- user32.dll exists
- antivirus is disable
I really love millennium. It works fine on my other pc.
But no idea why not working well on my new laptop...

**Comment by shdwmtr** [comment]
You are confident that when this issue happens, `user32.dll` is still in the Steam folder?

**Comment by RobloxGabriel1** [comment]
i think i have experienced it before. when i booted my pc up, it had a powershell warning.

**Comment by shdwmtr** [comment]
Try checking this issue out: https://github.com/SteamClientHomebrew/Millennium/issues/149

**Comment by shdwmtr** [comment]
Fixed in the latest release!
