### ISSUE TITLE
Work on linux 

### ISSUE THREAD

**Issue by uchihaitachi5099** [SteamClientHomebrew/Millennium#125]
### Before Reporting

- [x] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

Problem Description:

I'm having an issue with Millennium on Steam. I haven't made any changes to my Steam settings, yet the program is not creating the themes folder or the themes.json file inside the /home/itachi/.millennium/ext/ directory.

Whenever I run Millennium, it fails to find the themes because the themes.json file doesn't exist by default. Even when I manually create the themes.json file and the themes folder, the program still reports that the folder does not exist or that it cannot find the theme data.

It seems like Millennium is not correctly initializing or generating the necessary theme files and directories.
![image](https://github.com/user-attachments/assets/df05050f-b10a-4772-a8f6-2e364a55b31a)
here info about system

### Expected Behavior

I expect that when I run Millennium, the program should automatically create the themes folder and the themes.json file in the /home/itachi/.millennium/ext/ directory. Once these files are created, Millennium should be able to read the themes.json file and load the available themes without any errors.

Additionally, I expect that if I manually create the themes folder and themes.json file, Millennium should recognize them and function correctly, allowing me to access and utilize the themes as intended.

### Steps To Reproduce

    Install Steam: Make sure Steam is installed and running on your system.

    Install Millennium: Ensure that you have installed Millennium correctly in your home directory (~/.millennium).

    Check Steam Settings: Confirm that no changes have been made to the default Steam settings, particularly in the Library folder settings.

    Run Millennium: Start Millennium by executing the appropriate command in the terminal (e.g., bash ~/.steam/steam/steam.sh).

    Observe the Behavior: Notice that the themes folder and themes.json file are not created automatically in the /home/itachi/.millennium/ext/ directory.

    Manually Create themes.json: Attempt to manually create the themes folder and themes.json file in /home/itachi/.millennium/ext/.

    Run Millennium Again: Restart Millennium and observe the error message indicating that it cannot find the themes or that the folder does not exist.

    Check for Errors: Note any error messages displayed in the terminal regarding missing files or directories.

### Operating System

Linux

**Comment by shdwmtr** [comment]
Potentially a permission error with Millennium.

**Comment by uchihaitachi5099** [comment]
> Potentially a permission error with Millennium.

I try do found error with permission i try again but with sudo and did't work

**Comment by uchihaitachi5099** [comment]
when i delete steam and download it again i have this error STEAM XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xeb8a5860
STEAM XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xeb8a3fc0
STEAM /usr/share/themes/Yaru-blue-dark/gtk-2.0/main.rc:775: error: unexpected identifier 'direction', expected character '}'
STEAM /usr/share/themes/Yaru-blue-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
STEAM Fontconfig warning: line 5: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
STEAM Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
STEAM Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
STEAM Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
STEAM Fontconfig warning: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/10-yes-antialias.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
STEAM Fontconfig warning: "/etc/fonts/conf.d/70-no-bitmaps-except-emoji.conf", line 4: unknown element "description"

**Comment by shdwmtr** [comment]
Those are just font issuesm they wont cause any issues. `sudo` doesn't immediatly mean all permissions have been given, you may need to use `chmod`

**Comment by Playroom8775** [comment]
snap is a problem, /home/user/snap/steam/common/.local/share/Steam here is the path to steam which was installed by snap

**Comment by madmaxgrey** [comment]
> snap is a problem, /home/user/snap/steam/common/.local/share/Steam here is the path to steam which was installed by snap

we more than likely won't be supporting the snap and flatpak versions of steam as they are more complicated, and way too much overhead to deal with

**Comment by shdwmtr** [comment]
closing for no response.
