### ISSUE TITLE
[Bug] Plugin wont load

### ISSUE THREAD

**Issue by FenrirBots** [SteamClientHomebrew/Millennium#129]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

After building and moving the plugin to the plugins folder, millennium gets stuck loading the plugin.

### Expected Behavior

Millennium to load without issue.

### Steps To Reproduce

Copy examples/plugin
pnpm install
pnpm run dev
copy files to %programfiles(x86)%/steam/plugins/example

### Operating System

Windows

### Anything else?

[millennium-log.txt](https://github.com/user-attachments/files/17334150/millennium-log.txt)
[build-log.txt](https://github.com/user-attachments/files/17334151/build-log.txt)

**Comment by FenrirBots** [comment]
As an added note this also happens with npm install and npm run dev

**Comment by shdwmtr** [comment]
Yeah hot reload hasn't been fully implemented yet. I put it off since there were no plugins that needed immediate support. I plan to fix this soon.

**Comment by shdwmtr** [comment]
If you restart Steam it will load without issue *hopefully*

**Comment by FenrirBots** [comment]
This isnt happening while hot reloading, It happens when I start a new instance of steam.

**Comment by FenrirBots** [comment]
I recorded the whole thing but github wont allow mp4 videos to be uploaded so heres an unlisted video
https://youtu.be/SUx2m3cEvDk

**Comment by shdwmtr** [comment]
This seems to just be a bug with the sample plugin. I'll look into it!

**Comment by FenrirBots** [comment]
Fixed in pull request found at #130, This also comments out a line that throws errors.

**Comment by shdwmtr** [comment]
Fixed the issue at its root here https://github.com/SteamClientHomebrew/Millennium/commit/8624fab5942c684291edc1c0b8a090731dcd91c0
