### ISSUE TITLE
[Bug] Microsoft Defender detecting millennium.exe as thread.

### ISSUE THREAD

**Issue by mrugtangy** [SteamClientHomebrew/Millennium#134]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

The Microsoft defender is detecting millennium.exe as a thread. 
![image](https://github.com/user-attachments/assets/a315a3c3-7530-4a5d-b0e4-81923d3c3490)

### Expected Behavior

It shouldn't be detected as a thread. Might be a false positive, ig.

### Steps To Reproduce

Install millennium using the powershell script. 

### Operating System

Windows

**Comment by shdwmtr** [comment]
Weird. Usually the false positives come from user32.dll, not millennium.exe. Does user32.dll also get flagged?

**Comment by mrugtangy** [comment]
Nope. Only millennium.exe.

**Comment by shdwmtr** [comment]
Very weird considering we've never had issues with that, and the code for millennium.exe hasnt' been changed in months. I'm going to remove it from the next update as its not essential. I'll put it back once its fixed!
