### ISSUE TITLE
[Bug] Fail to disable steam remote debugging when uninstalling

### ISSUE THREAD

**Issue by EmilySunpy** [SteamClientHomebrew/Millennium#135]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

When running the uninstall script; it fails to remove the `.cef-enable-remote-debugging` file in the steam directory. Making steam always take up port `8080` which a lot of other applications also tend to use. I'm unsure if there is a real security risk as I don't know if steam limits connections to host or not.

### Expected Behavior

When uninstalling; remove the `.cef-enable-remote-debugging` file so steam don't keep remote debugging port open.

### Steps To Reproduce

1. Install Steam (and login)
2. Follow the install instructions to install Millennium
```powershell
iwr -useb "https://raw.githubusercontent.com/SteamClientHomebrew/Millennium/main/scripts/install.ps1" | iex
```
3. Uninstall Millennium
```powershell
iwr -useb "https://steambrew.app/uninstall.ps1" | iex
```

### Operating System

Windows

**Comment by madmaxgrey** [comment]
yes this is a requirement for steam and theming, millennium requires port 8080 to work

**Comment by shdwmtr** [comment]
That is true, it should be removed I'll change it. But no, it isnt a security risk.

**Comment by shdwmtr** [comment]
Fixed, https://github.com/SteamClientHomebrew/Millennium/commit/a923e2aca843c44ff8063db5169f33be8bce8ef7!

**Comment by jabuxas** [comment]
how can I disable it after uninstalling millennium on linux? still has that port open even when nuking all millennium artifacts

**Comment by ejalxndr** [comment]
@jabuxas `~/.steam/steam/.cef-enable-remote-debugging`
