### ISSUE TITLE
[Bug] Does Millennium seem to conflict with Steam Accelerator?

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#136]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

In China, sometimes a Steam accelerator is needed to ensure successful access to web pages on Steam, including Steam stores, creative workshops, and more. On some people's computers, using both Steam Accelerator and Millennium at the same time can cause web pages on Steam to not open properly. But it is normal to access the Steam website from the browser at this time. After uninstalling Millennium, the web pages in Steam returned to normal. I don't understand what caused this.
![06000712715961044CAB2BA860BDA0A2](https://github.com/user-attachments/assets/ded29b95-1e25-4912-9a14-b73e94558a39)

### Expected Behavior

I hope this phenomenon can be resolved

### Steps To Reproduce

Install Millennium and start Steam

### Operating System

Windows

**Comment by madmaxgrey** [comment]
more than likely that program your using is stealing port 8080 you cant have both that and millennium

**Comment by YCZ01111** [comment]
> more than likely that program your using is stealing port 8080 you cant have both that and millennium

If it's a problem with port 8080, shouldn't steam just fail to start?

**Comment by shdwmtr** [comment]
I dont know what Steam Accelerator is

**Comment by YCZ01111** [comment]
Just like a game accelerator, it accelerates Steam

**Comment by YCZ01111** [comment]
https://github.com/BeyondDimension/SteamTools
This is one of the steam accelerators for Chinese people

**Comment by shdwmtr** [comment]
I have no idea then, probably wont look into it either since I cant read chinese. Try some troubleshooting to see if it comes from Millennium
