### ISSUE TITLE
[Docs]: Typo in theme "Publishing" page

### ISSUE THREAD

**Issue by AdamRaichu** [SteamClientHomebrew/Millennium#137]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

There is a typo on [this page](https://docs.steambrew.app/developers/themes/publishing). (Normally I would just make a PR to fix it but idk where the docs are.)

### Expected Behavior

Under the "Guidelines" section, in this bullet point

 - Talking about anything other than you're theme
 
 `you're` should be `your`.

### Steps To Reproduce

https://docs.steambrew.app/developers/themes/publishing#guidelines

### Operating System

Windows

### Anything else?

(Sorry to be that guy, but grammar is grammar :D)

**Comment by shdwmtr** [comment]
Make a PR: 
https://github.com/shdwmtr/steambrew/blob/main/docs/ui/developers/themes/publishing.md
