### ISSUE TITLE
[Bug]The first launch of Steam after starting Windows fails

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#141]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

I use Steam Update Beta to adapt to the theme in a timely manner. There is a phenomenon where the first launch of Steam after starting Windows fails, but it can start normally after the second and subsequent launches. This phenomenon only appeared in recent days, is it related to beta?
![QQ浏览器截图20241020152611](https://github.com/user-attachments/assets/6103174d-1737-4ac3-b445-20cfc8225095)

### Expected Behavior

Successfully launched Steam for the first time after starting Windows

### Steps To Reproduce

1.start windows
2.start steam

### Operating System

Windows

**Comment by shdwmtr** [comment]
I think ive fixed this, I will be releasing the fix soon once I have enough bug testing

**Comment by YCZ01111** [comment]
Repeat with #149
