### ISSUE TITLE
[Feature] Overwrite Colors accents

### ISSUE THREAD

**Issue by spkesDE** [SteamClientHomebrew/Millennium#146]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

I would like to have the option to overwrite the accent color picked from Windows and maybe other colors.
Currently, it takes on the system accent color, which in my case is a dark gray. This results in a gray-on-gray appearance that isn't visually appealing. It would be great to have a setting in Fluenty to choose a custom accent color.
Thank you for considering this feature request!

**Comment by shdwmtr** [comment]
Great suggestion, I'll take a look into it right now!

**Comment by shdwmtr** [comment]
Implemented! https://github.com/SteamClientHomebrew/Millennium/commit/a850936e40688345a90646d92600cd6e506ea623. It will be in the next update.
