### ISSUE TITLE
[Bug]Millenium on Opensuse does not open

### ISSUE THREAD

**Issue by SteamRex25** [SteamClientHomebrew/Millennium#150]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

When I setup millenium on opensuse linux, steam would not open with millennium set as the default launch options at all

### Expected Behavior

when interacting with the desktop shortcut, Steam (and bu extension millennium) should open when millennium it set as the default launch option

### Steps To Reproduce

1. set the desktop or any menu interactive item for steam to launch millennium.
2. try and open steam only to see it not open

### Operating System

Linux

### Anything else?

![Screenshot_20241028_211035](https://github.com/user-attachments/assets/a827cab1-1d47-4d68-b22c-3c5e944ee5b5)

**Comment by shdwmtr** [comment]
If you've made a desktop shortcut not managed by Millennium the issue falls in your hands, I don't know what your shortcut does nor does it have official support. 

If you show me the shortcut I may have some idea, however its not garunteed.

**Comment by SteamRex25** [comment]
I wont be able to do that for a bit but I did include the errors I got from trying to run the script in the original issue post

**Comment by SteamRex25** [comment]
![Screenshot_20241029_192726](https://github.com/user-attachments/assets/94e246cd-2538-4aa4-bb23-b9e1836d47f9)
here is the setup of my desktop shortcut
