### ISSUE TITLE
[Bug]Reported an error but it did not affect usage

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#152]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

![image](https://github.com/user-attachments/assets/92f57367-c2f4-432f-a9f0-0c3d0d0ec0fb)

### Expected Behavior

I want to know if it affects

### Steps To Reproduce

1.start steam

### Operating System

Windows

**Comment by YCZ01111** [comment]
The error disappeared after restarting

**Comment by shdwmtr** [comment]
This is an issue with Steam. Anything labeled (Steam-Error) is an error from Steam, not something I wrote.
