### ISSUE TITLE
[Bug] Linux version crashing at everytime the command line is used to execute it

### ISSUE THREAD

**Issue by Xero646** [SteamClientHomebrew/Millennium#153]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

using the command ~/.millennium/start.sh
to turn millenium on results in a steam crash every single time, i have no idea why 
![unknown_001](https://github.com/user-attachments/assets/a1dabcc3-b518-43bc-b84d-6ff5ed3ef84a)

### Expected Behavior

everything has been installed properly so it should run fine, but... nope.

### Steps To Reproduce

1. use the automatic install prompt from millennium website for linux
2. install curl with pacman (i use arch btw)
3. run the start command 
4. crash

### Operating System

Linux

### Anything else?

nothing else to say here

**Comment by shdwmtr** [comment]
I'll take a look!

**Comment by shdwmtr** [comment]
Give this a go: https://github.com/SteamClientHomebrew/Millennium/actions/runs/11645070964. just extract it to ~/.millennium replacing all

**Comment by shdwmtr** [comment]
fixed

**Comment by dougbug589** [comment]
iam having the same issue startup crash . tried ur method but still its crashing 
![Uploading Screenshot_20241212_123453.png…]()
