### ISSUE TITLE
[Bug] Millennium doesn't download any theme on it's own and doesn't update theme list 

### ISSUE THREAD

**Issue by Xero646** [SteamClientHomebrew/Millennium#155]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme
- [X] My issue is not caused by a plugin

### Describe the Bug

when downloading a theme, Millennium doesn't show any prompt nor updates the theme download list if a theme was downloaded manually via an extracted .zip file
![unknown_005](https://github.com/user-attachments/assets/036b3f88-a6da-40ff-b6f8-c2e21898d28d)
![unknown_006](https://github.com/user-attachments/assets/8e9c8e03-22d7-4cd4-be34-957f1d9cb5be)

### Expected Behavior

opens a window to install theme making it usable and then applicable to steam, however it just downloads an empty folder 
![unknown_007](https://github.com/user-attachments/assets/8f70e2b9-6997-44b0-b7fd-d4a7369a5153)
![unknown_008](https://github.com/user-attachments/assets/944310a1-67b4-4be4-9d36-1bcf4ea69edc)

### Steps To Reproduce

1. use millennium on linux
2. download themes on millennium
3. restart and go to the themes section
4. notice that there's nothing showing up

### Operating System

Linux

### Anything else?

i have no idea why

**Comment by shdwmtr** [comment]
Are you installing from `steambrew.app`? Because I've recently made the decision to stop supporting auto theme management on linux, so that is likely the issue. You have to manually `git clone` the theme to `steamui/skins`. I will provide better documentation in the near future.

**Comment by Xero646** [comment]
Well I did use the website to do that as many did so for the windows version, then I tried to install a theme manually (the windows 95 one to match my desktop aesthetic) and it still doesn't seem to see it at all

**Comment by Xero646** [comment]
Well I did use the website to do that as many did so for the windows version, then I tried to install a theme manually (the windows 95 one to match my desktop aesthetic) and it still doesn't seem to see it at all

**Comment by shdwmtr** [comment]
It shows the folder is empty though?

**Comment by Xero646** [comment]
yup, it creates a folder but then aborts the download, as for the extracted win95 theme, the content is here, however, it doesn't refresh the theme list, thus it does not detect content at all

**Comment by shdwmtr** [comment]
yes `cd` to the theme and run both of those.

**Comment by Xero646** [comment]
![image](https://github.com/user-attachments/assets/a7c694bb-e0f0-4e2f-9c41-c4ef333698b1)
what to do next ? it says it is a folder and the root of it

**Comment by shdwmtr** [comment]
apologies, I meant `ls` instead of `cat`

**Comment by Xero646** [comment]
here you go, it is in here
![image](https://github.com/user-attachments/assets/6d11dc58-1705-4245-af2d-ed1031a737f4)

**Comment by Xero646** [comment]
fixed it, it was a double folder issue, however having the automatic downloader work on linux would be fantastic
![image](https://github.com/user-attachments/assets/9e815e5c-e98f-4cac-b2a1-c22681aa5de8)
