### ISSUE TITLE
Client notification position resets after Steam/PC restarts or resuming from sleep

### ISSUE THREAD

**Issue by MrManinBlack1337** [SteamClientHomebrew/Millennium#17]
![millenium](https://github.com/ShadowMonster99/millennium-steam-patcher/assets/87234960/60064491-133d-4405-8938-5c002826dbe9)

As the title says, the client notification position resets. I have checked the registry it still retains it settings as 0 (top left) but the Millennium UI and the Steam notification is back to the default location bottom right. Hopefully this is can be fixed because this is the only way to change Steam notification location afaik. Thank you

**Comment by ShadowMonster99** [comment]
So the client position is essentially instance specific? It doesn't save under any known circumstances? Even when closing steam and restarting normally?

Thanks for reporting this ill have a look in the near future however I am unsure when this will be addressed.
Cheers!

**Comment by MrManinBlack1337** [comment]
Yes it is instance specific. Even when closing steam and restarting normally.

Well good luck hopefully you got this

**Comment by ShadowMonster99** [comment]
Does the dropdown in the Millennium interface save across instances and just doesn't have effect? or is it also reset to "Bottom Right" everything startup

**Comment by MrManinBlack1337** [comment]
The dropdown works only for that instance, but when I restart Steam manually (or automatically like PC restarts/resume from sleep) it resets to Bottom Right

**Comment by shdwmtr** [comment]
Closed as its no longer planned to be implemented. It will likely be a plugin

**Comment by MrManinBlack1337** [comment]
When will this plugin ready by the way? Any ETA? I am currently holdin on on old version because I currently have a workaround for this bug. @shdwmtr

**Comment by shdwmtr** [comment]
I'm not entirely sure. I can't even give an ETA, could be a day, week, month or more. It just depends on when I get to it
