### ISSUE TITLE
it doent show up in the settings

### ISSUE THREAD

**Issue by ACR-NightLite** [SteamClientHomebrew/Millennium#18]
the lang. is turkish and the themes isn't on the settings.

**Comment by ShadowMonster99** [comment]
did you follow the installer correctly? have you tried restarting steam? have you tried restarting your PC?

**Comment by Linx-ESP** [comment]
Same issue in latest beta (not family sharing beta)

**Comment by ShadowMonster99** [comment]
> Same issue in latest beta (not family sharing beta)

Millennium only works for stable version of steam at the moment

**Comment by CorkScrewGnome** [comment]
This is also happening to me as well, a reinstall works, but only temporary.

**Comment by ShadowMonster99** [comment]
> This is also happening to me as well, a reinstall works, but only temporary.

I would need more context to help you solve that. 

- Are you on beta? 
- Have you tried [manually installing](https://github.com/SteamClientHomebrew/Millennium/wiki/Getting-Started#manual)? 
- What does temporary mean in this case?
   -  It only works for one Steam launch?
   -  It no longer works after restarting your PC?

**Comment by CorkScrewGnome** [comment]
No,
No, after a reinstall it works fine.
After one steam launch up to now it broke and required a reinstall.

**Comment by ShadowMonster99** [comment]
> No,
> 
> No, after a reinstall it works fine.
> 
> After one steam launch up to now it broke and required a reinstall.

Is it now working or are you still facing this issue?

**Comment by CorkScrewGnome** [comment]
Still facing issue.

**Comment by LukeyTWW** [comment]
The installer didn't work, even the manual installation.
Steam keeps hiding the skin selector (latest stable update).

**Comment by ShadowMonster99** [comment]
> The installer didn't work, even the manual installation. Steam keeps hiding the skin selector (latest stable update).

Do you have a file named millennium.log in the steam folder?

**Comment by LukeyTWW** [comment]
> > The installer didn't work, even the manual installation. Steam keeps hiding the skin selector (latest stable update).
> 
> Do you have a file named millennium.log in the steam folder?

yes i have the file
it says: "[22:54:28] [fail] Received malformed JSON response from websocket: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<' "

**Comment by ShadowMonster99** [comment]
> > > The installer didn't work, even the manual installation. Steam keeps hiding the skin selector (latest stable update).
> > 
> > 
> > Do you have a file named millennium.log in the steam folder?
> 
> yes i have the file it says: "[22:54:28] [fail] Received malformed JSON response from websocket: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: '<' "

Check out [this issue](https://github.com/SteamClientHomebrew/Millennium/issues/26). it seems like that's more than likely your issue

**Comment by litbeep** [comment]
Millennium no longer shows up for me in the Settings after the latest Steam client update (May 7). It installs just fine, and my chosen theme is even partially applied, there's simply no way to open the Millennium manager anymore.

Have already tried uninstalling and re-installing Millennium as well as rebooting the PC to no effect.

**Comment by ShadowMonster99** [comment]
> Millennium no longer shows up for me in the Settings after the latest Steam client update (May 7). It installs just fine, and my chosen theme is even partially applied, there's simply no way to open the Millennium manager anymore.
> 
> 
> 
> Have already tried uninstalling and re-installing Millennium as well as rebooting the PC to no effect.

Millennium is currently borked until it is fixed. Steam made changes breaking it. it will be fixed in the next few hours or days. check the discord for updates.

**Comment by Dav1d-Fn** [comment]
So, I'm using the steam beta (not the family one) and would like to stay with it. Will the fix be for the beta, or also just the stable version?

**Comment by shdwmtr** [comment]
Fixed in Millennium > 2.0.0
