### ISSUE TITLE
Millennium.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by Preloading** [SteamClientHomebrew/Millennium#21]
When opening the installer executable on Windows 7 (ultimate), I get an error

"The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll."
![image](https://github.com/ShadowMonster99/millennium-steam-patcher/assets/60761520/a9ea86ad-a926-40b4-be7e-93ed651b39d0)
This error message appears 3 times before stopping

Thanks for any help!

**Comment by Preloading** [comment]
Doing some googling, it seems like electron dropped support for windows 7, and this uses a newer electron version that doesn't support windows 7. Multiple other electron apps seem to have this exact same error ([here](https://discourse.joplinapp.org/t/news-windows-7-8-8-1-are-no-longer-supported-from-v2-12-7/32528), and [here](https://forum.obsidian.md/t/crash-new-electron-app-on-windows-7/60932)).

**Comment by ShadowMonster99** [comment]
Have you tried manually installing Millennium without using the installer?
https://millennium.gitbook.io/steam-patcher/getting-started/end-user/installation

**Comment by Preloading** [comment]
I just try it, but it errors on steam startup
![Millenium Stopped Working but better](https://github.com/ShadowMonster99/millennium-steam-patcher/assets/60761520/dd47e8d6-d635-466b-96e9-557693ee097a)

**Comment by Zorro-no** [comment]
> Have you tried manually installing Millennium without using the installer? https://millennium.gitbook.io/steam-patcher/getting-started/end-user/installation

i would but
![image](https://github.com/SteamClientHomebrew/Millennium/assets/108409246/60181bf2-fb90-445c-a6f0-c02d7917d4f0)

**Comment by ShadowMonster99** [comment]
> > Have you tried manually installing Millennium without using the installer? https://millennium.gitbook.io/steam-patcher/getting-started/end-user/installation
> 
> i would but ![image](https://private-user-images.githubusercontent.com/108409246/337717133-60181bf2-fb90-445c-a6f0-c02d7917d4f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzYwMTIsIm5iZiI6MTcxNzc3NTcxMiwicGF0aCI6Ii8xMDg0MDkyNDYvMzM3NzE3MTMzLTYwMTgxYmYyLWZiOTAtNDQ1Yy1hNmYwLWMwMmQ3OTE3ZDRmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTU1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTEzOTk0OWY3ZmQ2MGI2ODFjNTU5MjRlZWRhMGU4ZGRlMDJhNWQzMTQzMWQ5ZDVlYTQ4NjM1NTdlMjc5NjJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._sTmx_peOvQ2Nhuvb2iZ-3xi1AW8JriAf8Pf3nyLWDY)

https://github.com/SteamClientHomebrew/Millennium/wiki/Getting-Started#installation

**Comment by ShadowMonster99** [comment]
start steam and go to settings -> interface and look for open millennium. by your screenshot you provided though, it seems your on windows 7, which isn’t properly supported

**Comment by Zorro-no** [comment]
![image](https://github.com/SteamClientHomebrew/Millennium/assets/108409246/915d47b4-e929-4baa-a1d3-aee5b3a8bdfe)
sad

**Comment by shdwmtr** [comment]
Closed for inactivity, and for lack of planning to support Windows 7
