### ISSUE TITLE
[Bug] make not building on MacOS

### ISSUE THREAD

**Issue by LiamPalmqvist** [SteamClientHomebrew/Millennium#29]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

When compiling the program from clone on a unix based operating system such as MacOS, using make will get to 75% before failing. Majority of error is ```unknown type name 'fileName'```

### Expected Behavior

Expected the program to compile successfully.

### Steps To Reproduce

1. git clone --recursive https://github.com/SteamClientHomebrew/Millennium.git
2. cd Millennium
3. cmake -B build
4. cd build
5. make

the "make" command should fail to compile the program

### Operating System

Linux

**Comment by ShadowMonster99** [comment]
Millennium has no support for MacOS, as documented; and it's not currently planned unfortunately. If you want to contribute to Millennium on OSX feel welcome.

**Comment by plyght** [comment]
@shdwmtr any updates on Millennium for macOS?

**Comment by boehs** [comment]
Got a build, still broken but

```
evan@EvanAir cli % sudo ./millennium patch
Password:
Resolving permissions...
Error: Steam start script not found. Ensure you're Steam installation is not flatpak, or snap.
````

**Comment by boehs** [comment]
tried

```
evan@EvanAir millennium % export DYLD_INSERT_LIBRARIES="/Users/evan/Code/builds/millennium/build/libMillennium.dylib${DYLD_INSERT_LIBRARIES:+:$DYLD_INSERT_LIBRARIES}"
evan@EvanAir millennium % export DYLD_LIBRARY_PATH="/Users/evan/Code/builds/millennium/build/${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
evan@EvanAir millennium % /Applications/Steam.app/Contents/MacOS/steam_osx
```

but it didn't work maybe because of SIP

**Comment by shdwmtr** [comment]
Steams start script is entirely different on macos. You’ll have to figure out an entirely new way to start Millennium when steam starts

**Comment by boehs** [comment]
Yeah I'm working on it. Had a bit of better luck with `/Users/evan/Library/Application Support/Steam/Steam.AppBundle/Steam/Contents/MacOS`, got

```
dyld[21036]: terminating because inserted dylib '/Users/evan/Code/builds/millennium/build/libMillennium.dylib' could not be loaded: tried: '/Users/evan/Code/builds/millennium/build//libMillennium.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/evan/Code/builds/millennium/build/libMillennium.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Code/builds/millennium/build/libMillennium.dylib' (no such file), '/Users/evan/Code/builds/millennium/build/libMillennium.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
dyld[21036]: tried: '/Users/evan/Code/builds/millennium/build//libMillennium.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Users/evan/Code/builds/millennium/build/libMillennium.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/evan/Code/builds/millennium/build/lib
```

so rebuilding under x_86

**Comment by plyght** [comment]
hey @boehs any updates? do you think you could share your updated repo?
