### ISSUE TITLE
[Wiki]: Typo in FAQ page

### ISSUE THREAD

**Issue by AdamRaichu** [SteamClientHomebrew/Millennium#31]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

Original text:

> No, Millennium by itself does not alter Steam® in a manor that grants persons an unfair advantage, as well as it does not alter the intended operations of the service.

### Expected Behavior

`manor` should be `manner`

### Steps To Reproduce

https://github.com/SteamClientHomebrew/Millennium/wiki/Frequently-Asked-Questions#is-millennium-against-the-steam-terms-of-service-tos

### Operating System

Windows

### Anything else?

Perhaps this entire sentence could be rephrased in the following way:

> No, Millennium by itself neither alters Steam® in a manner that grants persons an unfair advantage, nor alters the intended operations of the service.

**Comment by ShadowMonster99** [comment]
Thanks, updated it!
