### ISSUE TITLE
[Bug] Fails to build due to missing Windows.h on Linux

### ISSUE THREAD

**Issue by tcharchar** [SteamClientHomebrew/Millennium#33]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

When attempting to build with `make`, at ~75% the build stops with: 
```
[ 75%] Building CXX object CMakeFiles/millennium.dir/src/core/injector/event_handler.cpp.o
In file included from /home/coal/builds/Millennium/src/core/injector/event_handler.cpp:23:
/home/coal/builds/Millennium/src/utils/io/ports.hpp:4:10: fatal error: Windows.h: No such file or directory
    4 | #include <Windows.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

I'm using Arch Linux, with 6.8.6-zen1-1-zen as my kernel. 
I'm uncertain of any needed dependencies, as there are none listed.

### Expected Behavior

For Millenium to Build correctly.

### Steps To Reproduce

1. Clone the repository with `--recursive`.
2. Execute `cmake -B` and `make`
3. During `make`, build stops.

### Operating System

Linux

**Comment by ShadowMonster99** [comment]
I haven't updated the wiki, but one of the recent commits borked Linux build support. try a somewhat older commit oid. Even if you get it working its not in a spot where I'd recommend using it as an end-user. We are currently rewriting Millennium and it would probably be best to just wait until then!

Cheers!

**Comment by tcharchar** [comment]
> I haven't updated the wiki, but one of the recent commits borked Linux build support. try a somewhat older commit oid. Even if you get it working its not in a spot where I'd recommend using it as an end-user. We are currently rewriting Millennium and it would probably be best to just wait until then!
> 
> Cheers!

Thank you! I'll wait until the linux build functions again, as Steam is not my priority regardless due to me using wayland + a tiling WM. (and a Nvidia card to top it off)
