### ISSUE TITLE
[Feature] pls support linux

### ISSUE THREAD

**Issue by SteavenGamerYT** [SteamClientHomebrew/Millennium#34]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

pls add linux support

### Anything else?

i would like to use it on linux, steam flatpak

**Comment by ShadowMonster99** [comment]
Support is coming? its mentioned in the readme
