### ISSUE TITLE
[Bug] Access violation error when closing steam

### ISSUE THREAD

**Issue by tommy141x** [SteamClientHomebrew/Millennium#38]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

When closing steam, either through "Exit Steam" or switching accounts, or shutting down the PC. I receive a memory application error. This only happens with Millennium installed.
![image](https://github.com/SteamClientHomebrew/Millennium/assets/57594516/045ed476-7d81-4eb4-bf67-45f1a897467d)

`Exception thrown at 0x693312B4 (User32.dll) in steam.exe: 0xC0000005: Access violation reading location 0x683275C0.`

### Expected Behavior

No error popup when closing steam

### Steps To Reproduce

On Windows 11 Pro 23H2 (22631.3296), install Steam, then install Millennium, and close steam.

### Operating System

Windows

### Anything else?

I do have a windows playbook installed which I know modifies some of the core operating system components/services. So this entire issue may just be a result of that. However this issue only occurs with Millennium installed, so that is why I created this issue.

**Comment by ShadowMonster99** [comment]
This issue has and will be fixed in the next major release!
