### ISSUE TITLE
[Bug] Themes aren't showing up after installing

### ISSUE THREAD

**Issue by AzimuthUwU** [SteamClientHomebrew/Millennium#41]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

after installing the themes arent showing up, even after restarting steam multiple times, and after restarting the computer

### Expected Behavior

It should show the themes after refreshing the list

### Steps To Reproduce

idk, i just dont work

### Operating System

Windows

**Comment by ShadowMonster99** [comment]
Ensure all themes in the skins folder have a skin.json in the root directory of the skin folder. Also ensure you have your themes in the right spot.

- `steamui/skins/themeName/skin.json` as opposed to `steamui/skins/themeName/themeName/skin.json`
- default steamui directory is `C:\Program Files (x86)\Steam\steamui`

**Comment by AzimuthUwU** [comment]
> Ensure all themes in the skins folder have a skin.json in the root directory of the skin folder. Also ensure you have your themes in the right spot.
> 
> * `steamui/skins/themeName/skin.json` as opposed to `steamui/skins/themeName/themeName/skin.json`
> * default steamui directory is `C:\Program Files (x86)\Steam\steamui`

thank you, i realized my errors
