### ISSUE TITLE
[Feature] Add support for multiple languages

### ISSUE THREAD

**Issue by Patrxgt** [SteamClientHomebrew/Millennium#42]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

It would be nice, if Millennium had a support for multiple languages. The language could even be selected automatically, depending on the language of the Steam client.

**Comment by ShadowMonster99** [comment]
I agree, this feature isn't currently in the works, but it's planned. It might be in a newer update in the next few weeks.

**Comment by ShadowMonster99** [comment]
Closed as completed. We've added language support for multiple languages on the dev build!
