### ISSUE TITLE
[Question/Bug?] Can I add SpaceTheme to Steam web

### ISSUE THREAD

**Issue by QWERTYkeyboards124** [SteamClientHomebrew/Millennium#43]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

I wanna make the steam website in my steam client's store and more look like spacetheme

### Expected Behavior

I wanna have the website look like the library
![image](https://github.com/SteamClientHomebrew/Millennium/assets/97314746/f02412fb-5eb2-4867-bfa1-1ae2a7e57c2f)
![image](https://github.com/SteamClientHomebrew/Millennium/assets/97314746/6e910e32-84ec-4911-ac92-86d5d08e3230)

### Steps To Reproduce

1.Install Spacetheme
2.See that there is no web theme :(.

### Operating System

Windows

**Comment by ShadowMonster99** [comment]
Not a Millennium issue. you checked the boxed stating this isn't a theme issue, however it is. Contact the theme developer.
