### ISSUE TITLE
[Bug] error getting websocketdebuggerUrl: unknown exception

### ISSUE THREAD

**Issue by The-Observer1984** [SteamClientHomebrew/Millennium#46]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

millennium steam error getting websocketdebuggerUrl: unknown exception, no place to find skins in steam

### Expected Behavior

no popup and finding the skins in interface

### Steps To Reproduce

1. run windows 10
2. download steam
3. (optional) close steam
4. run the automatic millenium download
5. open steam

### Operating System

Windows

### Anything else?

If i have not provided enough info i will happily provide :3

**Comment by ShadowMonster99** [comment]
Duplicate of #26
