### ISSUE TITLE
[Bug] Millennium Installer fails to fetch over Ethernet but works over WiFi?

### ISSUE THREAD

**Issue by lazerl0rd** [SteamClientHomebrew/Millennium#47]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

Millennium Installer fails to fetch resources over Ethernet but works over WiFi [on the same Network]. I've tested two seperate interfaces - an ASIX AX88179-based Adapter and a Realtek Adapter (the one on the Dell WD19TB Docking Station).

Note: There is a chance that this problem isn't caused by Millennium [Installer] (given its weird nature), however I haven't seen similar behaviour in any other software.

### Expected Behavior

Millenium Installer fetches the required resources correctly on either connection.

### Steps To Reproduce

1. Download `Millennium.Installer-Windows.exe` from https://github.com/SteamClientHomebrew/Installer/releases.

2. Run `Millennium.Installer-Windows.exe`.

3. Click "Install".

4. Steam is closed if running, and the error (attached below) appears after a short wait.

### Operating System

Windows

### Anything else?

Here is the error I recieved:

![image](https://github.com/SteamClientHomebrew/Millennium/assets/24303423/302a342b-943c-4287-bac4-3fc3e4d48406)

**Comment by madmaxgrey** [comment]
hey lazer sorry for the late reply, can you try manually installing millennium you can get the binary files here
https://github.com/ShadowMonster99/millennium-steam-binaries/releases
download both the user32.dll & boost_random-vc143-mt-x32-1_79.dll files and copy them directy to this location C:\Program Files (x86)\Steam
and make sure steam is fully closed before doing so 


you may also need these 3 other dependencies that weren't install when you ran the installer

https://aka.ms/vs/17/release/vc_redist.x86.exe
https://aka.ms/vs/17/release/vc_redist.x64.exe
https://www.microsoft.com/en-ca/download/details.aspx?id=35

if its still not working please let us know

**Comment by lazerl0rd** [comment]
I should be able to manually install since it installed over WiFi just fine - Ethernet (two seperate adapters) is where I encountered issues. The only thought that comes to mind is I have Jumbo Frames enabled (at 9K) - but that should be abstraced away and not affect the Installer I would think.

**Comment by madmaxgrey** [comment]
could be various of reasons why it happened there's no 1 solid answer but i'm glad to know it's working fine for you, also be sure to come join our discord if you haven't already heres the invite link
https://discord.com/invite/NcNMP6r2Cw

**Comment by lazerl0rd** [comment]
So as wild as this sounds... seems like GOG Galaxy was the cause (also the cause for Steam not opening half the time, EA client being broken, and Riot Client not opening)... I'm very confused at this point but too exhasted to figure out what happened.
