### ISSUE TITLE
theme's seem to break when puttin the device into sleep-mode, sometimes

### ISSUE THREAD

**Issue by GrubPL** [SteamClientHomebrew/Millennium#49]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

sometimes when i just turn my device back from sleep-mode, the whole theme funcionality seems to, not work, so lets say a theme has modified the workshop page for example, that whole thing, will stop working, after changing the theme, it just dosent work

### Expected Behavior

it shouldnt do that, at all

### Steps To Reproduce

i guess just put the device into sleep mode, it just seems to happen, im not even sure sleep-mode causes it, but so far it only happend to me whenever i had it in sleep-mode

### Operating System

Windows

**Comment by ShadowMonster99** [comment]
Don’t worry you’re not crazy, this is a known issue planned to be fixed in the next update! I’ll keep this issue open until i’m sure it’s fixed. 

Cheers!

**Comment by shdwmtr** [comment]
Fixed in Millennium version > 2.0.0
