### ISSUE TITLE
[Bug] failed to load rendersystemdx11.dll

### ISSUE THREAD

**Issue by Beezbeatsaber** [SteamClientHomebrew/Millennium#55]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

This is causing my CS2 ive also heard it can break dota2 to give an error related to "failed to load rendersystemdx11.dll"
this only happened after installing millennium

### Expected Behavior

launch cs2 and be able to play competitive.

### Steps To Reproduce

1. launch cs2 with Millennium installed
2. gives a "failed to load rendersystemdx11.dll" error

### Operating System

Windows

**Comment by Beezbeatsaber** [comment]
the CS2 stop crashing after i removed millennium.

**Comment by ShadowMonster99** [comment]
Have you tried anything to fix this? 

From a glance I see [this](https://github.com/ValveSoftware/Dota2-Gameplay/issues/2597)

**Comment by Beezbeatsaber** [comment]
Microsoft Visual C++ 2015
is already installed

launching the game via .EXE disables VAC, Therefore competitive is disabled.

**Comment by ShadowMonster99** [comment]
In your steam folder, find User32.dll and delete it. then try CS. if it works, try to create a new text file and name it User32.dll (essentially just an empty renamed text file) in the same spot you deleted it from and try that

**Comment by ShadowMonster99** [comment]
Just an update, not sure if you've fixed this, but I've heard back from some community members that CS2 competitive plays fine with and without millennium.

**Comment by ShadowMonster99** [comment]
Closing due to no response
