### ISSUE TITLE
[Bug] Unable to build due to CPR requirement

### ISSUE THREAD

**Issue by LunaMeadows** [SteamClientHomebrew/Millennium#57]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

When I attempt to do cmake -B build, the command errors out stating it is unable to locate the cpr package. I could not confirm which cpr package is actually needed but I assume it is https://github.com/libcpr/cpr based on the vcpkg files mentioning it. I installed it how it is stated and tried setting cpr_DIR variable but nothing seemed to work.

> CMake Error at CMakeLists.txt:53 (find_package):
  Could not find a package configuration file provided by "cpr" with any of
  the following names:
  cprConfig.cmake
  cpr-config.cmake
  Add the installation prefix of "cpr" to CMAKE_PREFIX_PATH or set "cpr_DIR"
  to a directory containing one of the above files.  If "cpr" provides a
  separate development package or SDK, be sure it has been installed.

### Expected Behavior

cmake would detect cpr and move onto the next requirement

### Steps To Reproduce

Run cmake -B build in ubuntu 20.04

### Operating System

Linux

**Comment by ShadowMonster99** [comment]
Run `cmake --preset=linux` to configure cache properly

**Comment by LunaMeadows** [comment]
That fixed it, thanks!
