### ISSUE TITLE
[Bug] Unexpected Application Error: n.reduce is not a function

### ISSUE THREAD

**Issue by skiwidiwi** [SteamClientHomebrew/Millennium#61]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

I had just downloaded the installer, and when I hit install and next, it showed that page immediately. I checked the troubleshooting page and installed the millennium binaries manually, but nothing changed.

### Expected Behavior

I expected the application to install.

### Steps To Reproduce

1. Download & Run Installer
2. Click Install
3. Click Next

### Operating System

Windows

### Anything else?

![image](https://github.com/SteamClientHomebrew/Millennium/assets/142080395/f313848a-2ff2-48d3-8ebe-ba7547fb7cba)

**Comment by ShadowMonster99** [comment]
You're most likely using the wrong version of the installer. 

are you downloading it from here?
https://github.com/SteamClientHomebrew/Installer

**Comment by ShadowMonster99** [comment]
Closed for no response
