### ISSUE TITLE
[Bug] Steam reload uninstalls Millennium without quitting Steam.

### ISSUE THREAD

**Issue by mrwallace888** [SteamClientHomebrew/Millennium#63]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

This may actually be related to #49 but I don't know for sure. Whenever my computer wakes from sleep mode, Millenium still works.

My issues arise whenever Steam reloads. For some reason Steam likes to reload itself. Not quit and restart, just reload all the windows. Usually this is caused from me doing something like, say, exiting out of SteamVR. Or sometimes it just does it on its own, like if my computer has high usage temporarily or something, it'll close out all the Steam windows, and when I reopen it, Millennium is gone.

I'm not really sure what's happening internally, but I find it weird how Steam seems to automatically uninstall Millenium without Steam ever actually quitting or restarting. Just reloading the windows for some reason seems to be enough. Unless it's not fully uninstalling it and it just strangely removes some of Millenium's important stuff. My current theme resets back to standard, and the "Open Millennium" button is no longer in the settings so I can't reapply it. I have to keep reinstalling Millennium at times and it can get tedious.

### Expected Behavior

I expected it to not remove itself somehow.

### Steps To Reproduce

Not really sure how specifically to reproduce it. Steam just occasionally prompts a reload (it'll even say in the main Steam window "Reloading Steam", followed by the windows closing themselves out, and when I reopen the Steam windows, Millennium's gone). The only semi-consistent way I can think of causing the reload is when I close out of SteamVR sometimes.

### Operating System

Windows

**Comment by ShadowMonster99** [comment]
Thanks for reporting this issues, and thanks for an in depth explanation of the problem! Are you currently running the stable public version of Millennium? i.e. the version downloaded from https://steambrew.app? If so, you can try the new beta version of Millennium (which you can [install here](https://docs.steambrew.app/users/installing)) and it may fix your issue!

Happy patching :)

**Comment by mrwallace888** [comment]
I'm using stable, yeah. I can try the beta I guess and we'll see what happens. Was #49 known to be fixed in the beta? Because if that's the case then if it's related to my issue, it might fix it too.

**Comment by ShadowMonster99** [comment]
Yes, it was fixed in the latest beta. Give the beta a go if you'd like.

**Comment by mrwallace888** [comment]
The link you provided to install the beta is unclear. Does that Powershell script install the beta or does it install the latest stable? Because when I used the script it didn't say anything about installing a beta, it just asks if I want to enable auto-updating (excluding beta).

**Comment by ShadowMonster99** [comment]
> The link you provided to install the beta is unclear. It just provides instructions on using Powershell scripts to install Millennium, it says nothing about installing a beta and the Powershell script installs the latest stable.

The script automatically installs the beta version of Millennium. It doesn't let you install stable.

**Comment by ShadowMonster99** [comment]
Any news here?

**Comment by ShadowMonster99** [comment]
Closing for no response
