### ISSUE TITLE
[Bug] [BETA] Broken themes

### ISSUE THREAD

**Issue by Lymiix** [SteamClientHomebrew/Millennium#67]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by a theme

### Describe the Bug

Almost all the themes that I install are broken, some are displayed incorrectly, and some even make Steam glitch. This all appeared after switching to the Beta version. I switched to beta only because my “Millennium” button disappeared and I couldn’t select themes.
P.S. All themes I re-install before

https://github.com/user-attachments/assets/bf92966e-ea08-4670-9025-fbc3193d72e3

### Expected Behavior

I want working themes

### Steps To Reproduce

1. Turn on Steam and apply any theme.
2. Restart Steam

### Operating System

Windows

**Comment by ShadowMonster99** [comment]
Not a Millennium issue. Steam has changed components of the interface that will require theme authors to update their themes
