### ISSUE TITLE
[Bug] CSS root is not patched correctly on webpages

### ISSUE THREAD

**Issue by SpaceEnergy** [SteamClientHomebrew/Millennium#69]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

CSS root colors are displayed in the DevTools but are not recognized by CSS and are therefore greyed out

### Expected Behavior

The CSS should recognize the variable and use its color

### Steps To Reproduce

1. add a variable color for the scrollbar
1. use `"RootColors": ""` in skin.json
1. open the store page or steamcommunity.com in Steam and have a look at the scrollbars

### Operating System

Windows

### Anything else?

![image](https://github.com/user-attachments/assets/efe05db5-2b31-4ede-850b-a06fb1b70ddc)
![image](https://github.com/user-attachments/assets/a5eee26f-e056-4db5-bd52-aa11ba43d757)

**Comment by SpaceEnergy** [comment]
oh....... nvm is my mistake XD

**Comment by SpaceEnergy** [comment]
but do you have another solution how to do this so that it works with the system accent colors because if i import them normally then they are always like this even if the option is off

**Comment by ShadowMonster99** [comment]
> but do you have another solution how to do this so that it works with the system accent colors because if i import them normally then they are always like this even if the option is off

What do you mean "so that it works with the system accent colors"?

**Comment by SpaceEnergy** [comment]
hmm,
I also have in the skin.json
```json
        "System accent colors": {
            "description": "Replaces the SpaceTheme accent colors with your system accent colors",
            "default": "no",
            "values": {
                "no": {},
                "yes": {
                    "TargetCss": { "affects": [".*"], "src": "options/systemAccent.css" }
                }
            }
        },
```
inside
and systemAccent.css only changes 2 accent variables, and if I have the option "System accent colors" on, the css file is not patched into the webpages (so the one at the top xd)

Translated with www.DeepL.com/Translator (free version)

**Comment by SpaceEnergy** [comment]
if you want to have a look yourself you can use the files i sent you via DM in discord

**Comment by ShadowMonster99** [comment]
So your issue is that dynamic patching doesn't inject CSS into the webpages?

**Comment by SpaceEnergy** [comment]
basically yes

**Comment by shdwmtr** [comment]
I've finally found time to address this. I'm thinking of reimplementing web-patching based off of URL regex matching like it used to, which I can't see being problematic. 

Like:

```json
"System accent colors": {
    "description": "Replaces the SpaceTheme accent colors with your system accent colors",
    "default": "no",
    "values": {
        "no": {},
        "yes": {
            // .* will affect steam store, and so will https://*.steampowered.com
            "TargetCss": { "affects": [".*", "https://*.steampowered.com"], "src": "options/systemAccent.css" }
        }
    }
}
```

or for static patching:
```json
{
    "MatchRegexString": "https://*.steampowered.com",
    "TargetCss": "src/styles/loginView.css"
}
```

Once I look into it deeper, I'll see if this is actually doable.
