### ISSUE TITLE
"Open Millennium" button doesn't always appear in the "Interface" category in Steam Settings

### ISSUE THREAD

**Issue by Githubistheworst** [SteamClientHomebrew/Millennium#70]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

The title really says it all. Under the "Interface" category in Steam settings, the "Open Millennium" button doesn't always appear. So this basically means that, sometimes, I can't change my theme.

### Expected Behavior

I expected the "Open Millennium" button to always appear.

### Steps To Reproduce

1. Select the Steam menu at the top left
2. Select "Settings"
3. Select "Interface"
4. The button isn't always there

### Operating System

Windows

**Comment by ShadowMonster99** [comment]
Switch to Millenniums beta, it has a plethora of fixes for stuff like this!
https://docs.steambrew.app/users/installing
