### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zgwsww** [SteamClientHomebrew/Millennium#72]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

Open Millennium is not shown in the steam interface. Steam will not appear if you switch to beta or home beta. This open millennium appears when no beta is selected. Hope that the author can be improved to fix this bug. Can be used in any beta version.

### Expected Behavior

Open Millennium is not shown in the steam interface. Steam will not appear if you switch to beta or home beta. This open millennium appears when no beta is selected. Hope that the author can be improved to fix this bug. Can be used in any beta version.

### Steps To Reproduce

Open Millennium is not shown in the steam interface. Steam will not appear if you switch to beta or home beta. This open millennium appears when no beta is selected. Hope that the author can be improved to fix this bug. Can be used in any beta version.

### Operating System

Windows

### Anything else?

Open Millennium is not shown in the steam interface. Steam will not appear if you switch to beta or home beta. This open millennium appears when no beta is selected. Hope that the author can be improved to fix this bug. Can be used in any beta version.

**Comment by ShadowMonster99** [comment]
Use Millennium beta. 
https://docs.steambrew.app/users/installing
