### ISSUE TITLE
[Bug] Millenium Beta is completely broken right now.

### ISSUE THREAD

**Issue by mrwallace888** [SteamClientHomebrew/Millennium#73]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

I first noticed when starting up my PC that Steam would say "installing update" and then immediately stop. All of Steam's processes would disappear from Task Manager. If I started Steam again, it would just do the same thing, install an update and close. I uninstalled Millennium and it fixed it, but when I tried reinstalling Millennium, this happened instead.
![image](https://github.com/user-attachments/assets/31173cb0-5453-4c23-88cd-aaa03bfbb8b7)

If I try to start Steam anyways, nothing happens, it shows up in the process list but I can't see anything. Minutes later, a popup appears saying that steamwebhelper is not responding and Steam asks me how to fix it (exit Steam, restart Steam, restart steamwebhelper, etc.).

### Expected Behavior

I expected it to not cause Steam to mess up. Not sure if Steam had a big update today or something as this worked fine yesterday.

### Steps To Reproduce

Not really sure what kind of steps. I just noticed Steam wasn't working, so I uninstalled and then installed the beta via the Powershell script.

### Operating System

Windows

**Comment by ShadowMonster99** [comment]
There was a bug in Millennium's CI causing it to loop like that. Luckily we fixed it in a few minutes. 
Even after completely reinstalling though, you're still facing issues?

**Comment by mrwallace888** [comment]
Uhh it did it when I tried a couple hours later after posting this issue still. But I'll try again later I guess and see it does.

**Comment by ShadowMonster99** [comment]
Anything?

**Comment by mrwallace888** [comment]
I tried installing today and the issue persists. Steam just shows up only in my little shelf on the right side of the taskbar, but attempting to interact with Steam makes the window still pop up saying Web Helper is not working.
![image](https://github.com/user-attachments/assets/f2c85164-ad0d-4334-bbfb-605d08ebf37e)
![image](https://github.com/user-attachments/assets/29c61454-a2a1-4133-9d76-75935268608d)

**Comment by ShadowMonster99** [comment]
Try updating to the latest version, Some bug fixes have been made

**Comment by mrwallace888** [comment]
Still the same issue as before. Powershell still says that all my themes' access is denied and that the core has had an error checking for updates.

What has gone wrong?

**Comment by shdwmtr** [comment]
@mrwallace888 Show me the console output.

**Comment by mrwallace888** [comment]
I don't know what you're referring to apart from the Powershell output, which is the exact same as before. Access is denied with all my themes and then without being verbose it simply just says that the core had an error checking for updates.

**Comment by shdwmtr** [comment]
Completely forgot about this issue, but has it been resolved; or have you given up.

**Comment by mrwallace888** [comment]
I gave up. Still just has issues. Was there literally nothing useful in that PS output that could help to solve it?

**Comment by shdwmtr** [comment]
Anything is helpful, I can't magically find an issue on someone elses PC. You can try the latest version which has had some bug fixes surrounding this, or if not I can close this :)

**Comment by mrwallace888** [comment]
Well I'm just saying I wish the log was way more verbose than it is because just saying the core had an error when checking for updates doesn't really give much to work with. Or like I can't figure out why it's saying "access denied" for the themes.

I'll try this again later.

**Comment by shdwmtr** [comment]
There isnt any further information because it wasnt overly important. Either way, that has since been entirely removed :)

**Comment by shdwmtr** [comment]
Give this a go: https://github.com/SteamClientHomebrew/Millennium/issues/149
