### ISSUE TITLE
[Bug] Millenium is opening the CMD with Steam

### ISSUE THREAD

**Issue by dgsmiley18** [SteamClientHomebrew/Millennium#74]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

Hello, when i installed Millenium a few months ago it didn't open cmd with steam, but now it does and if i close the CMD, it will close steam too, is there an option to disable or is it permanent?
![steam_ixKMfijNop](https://github.com/user-attachments/assets/be2b0e6d-3ea0-4827-b6d9-a701b2c3ab99)

### Expected Behavior

i expected to only open steam

### Steps To Reproduce

> Install Millenium
> Open Steam

### Operating System

Windows

**Comment by dgsmiley18** [comment]
![image](https://github.com/user-attachments/assets/90264bf0-1d9c-4b95-a478-1d38b271e1ea)
Ok, i discovered this thing in my shortcut and i removed it and now steam opened without the CMD, is there a possibility in the future of this being optional? like a button in the installer "Do you want to activate the log?"

**Comment by ShadowMonster99** [comment]
It will likely stay as it is for a while. You should only need to launch steam with -dev if your developing a theme/plugin regardless.
