### ISSUE TITLE
[Help] How exactly do you even install?

### ISSUE THREAD

**Issue by Kafeecooker** [SteamClientHomebrew/Millennium#75]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

I'm on Linux, but the installation instructions are so vague, I have no idea what to even do. You just say "Simply put all files into your Steam directory, which should be ~/.local/share/Steam/" 

Which I did... But then what? Is that it? I don't even see anything related to Millennium or homebrew in my interface settings. I don't know anything about installing because the instructions are so empty. No screenshots or anything? Do I start the 'sh.' file you included? 

Please, I have no idea what to even do, at least give me an actual example of a successful install procedure on Linux! Thank you.

### Expected Behavior

An install? Something in the settings? Maybe a window popup saying: Congratulations for installing Millennium? How can I know if you don't even properly tell me how to install it?

### Steps To Reproduce

Extract the tar.gz to steam directory, then I imagine something happens, but I have no idea.

### Operating System

Linux

### Anything else?

![WHAT?!](https://github.com/user-attachments/assets/de30fb8d-bcbf-4e6a-99d0-250f7567ad08)

**Comment by ShadowMonster99** [comment]
I just haven't gotten to properly documenting the linux version as it isn't really ready. In the last few days I've made progress on the linux build, and essentially all that documentation is now obsolete (even though it isn't much anyways). As of now, running `~/.millennium/start.sh` (after you install with the script) will start Steam with Millennium. In the near future though, running just `steam` or how you originally start it will be good enough. 

You can contribute to the [documentation](https://github.com/SteamClientHomebrew/Docs) if you feel as if something is needed, everything is best effort. 
Cheers!

**Comment by Kafeecooker** [comment]
I put all the millennium files in the steam directory. So, I made the sh. script executable using chmod +x, then ran it. I get that. But it just launches steam? Is there supposed to be a install window for millennium or do I go into settings? Because I don't see anything there.

![terminal output](https://github.com/user-attachments/assets/ec66bce8-9803-4cee-91cb-97da127bb828)
![ads](https://github.com/user-attachments/assets/9b84f6d7-3384-4901-bf5e-bbf60cc16d77)

Am I really just doing this wrong? Do I run chmod +x on start.sh before putting it in the steam directory? Because I extracted the tar.gz contents to a folder named "millennium" then copied the contents to the steam directory. Ran it there, nothing really changed, no windows, popups, nothing. I really hope I'm not like missing a crucial step, because I barely know how terminal works..

**Comment by ieee802dot11ac** [comment]
Adding onto this, `start.sh` uses an incorrect LD_PRELOAD that makes it not work. Using the following exports in place of the erroneous line makes the script not error out, but it still doesn't work.
`export LD_PRELOAD=~/.millennium/libMillennium.so # preload Millennium into Steam
export LD_LIBRARY_PATH=~/.millennium/`

**Comment by ShadowMonster99** [comment]
@ieee802dot11ac  Yeah, I noticed a few hours ago I accidentally hard-coded paths specific to the build slave. Make a pull request and I'll merge it!

**Comment by ShadowMonster99** [comment]
Thanks for reporting these issues, Some bugs come up that aren't on the Windows version of Millennium. I'm relatively confident dad87ba8ba76f4df4ff033f14f68d2c53651a85f should fix all issues with running Millennium!

**Comment by ShadowMonster99** [comment]
I've also updated the docs to be more clear, thanks for bringing it to my attention. https://docs.steambrew.app/users/installing.

**Comment by su226** [comment]
> Keep in mind you should do `export LD_LIBRARY_PATH=~/.millennium/:$LD_LIBRARY_PATH` as to not override the externally provided paths.

Actually, you should use `export LD_LIBRARY_PATH="~/.millennium/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"` to avoid LD_LIBRARY_PATH becoming `~/.millennium/:` (with a trailing colon)

**Comment by ShadowMonster99** [comment]
> > Keep in mind you should do `export LD_LIBRARY_PATH=~/.millennium/:$LD_LIBRARY_PATH` as to not override the externally provided paths.
> 
> Actually, you should use `export LD_LIBRARY_PATH="~/.millennium/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"` to avoid LD_LIBRARY_PATH becoming `~/.millennium/:` (with a trailing colon)
> 
> Also, use doublequotes to avoid bash's space quirks.
> 
> And the same applies to LD_PRELOAD: `export LD_PRELOAD="~/.millennium/libMillennium.so:${LD_PRELOAD:+:$LD_PRELOAD}"`

I see. You can make a pull request on the [start script](https://github.com/SteamClientHomebrew/Millennium/blob/main/scripts/posix/start.sh) then in that case. I'm not much of a linux user.

**Comment by Kafeecooker** [comment]
well, it launched steam. how do i install themes now?

**Comment by ShadowMonster99** [comment]
> well, it launched steam. how do i install themes now?

There were a few bugs preventing millennium from working on the latest build; that I've since fixed. Just wait for the new release and it will work then (a day max). I only started porting about last week, so you'll have to stick with me.

**Comment by Kafeecooker** [comment]
okie dokie take your time :)

**Comment by shdwmtr** [comment]
Everything has since been fixed in the new version of Millennium.
