### ISSUE TITLE
[Bug] failed to load rendersystemdx11.dll CS2

### ISSUE THREAD

**Issue by uppofig** [SteamClientHomebrew/Millennium#78]
### Before Reporting

- [X] I found no existing issues matching my bug
- [x] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

The game can only be launched via a shortcut in Steam, and this error appears when starting Dota 2.

Can it happend with actual AMD driver?
Latest driver from old system named 19.x.x.

### Expected Behavior

All drivers, system, VCRedist, has been updated, and much more, But nothing gonna work, This starts after reinstalling windows.
System has been downloaded from official microsoft website. 
Before reinstallation, everything worked without errors. 

### Steps To Reproduce

This starts after reinstalling windows.
System has been downloaded from official microsoft website. 
Before reinstallation, everything worked without errors. 
Can it happend with actual AMD driver?
Latest driver from old system named 19.x.x.

### Operating System

Windows

### Anything else?

![изображение](https://github.com/user-attachments/assets/aad465d8-4bbd-4316-a6d0-12f9a36ebece)

**Comment by ShadowMonster99** [comment]
Why are you inclined to believe this issue stems from Millennium? This seems unrelated entirely.
