### ISSUE TITLE
[Bug] Issues with Steam showing on fresh install

### ISSUE THREAD

**Issue by Leandro050PT** [SteamClientHomebrew/Millennium#81]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

After a system restart, or just a change of account, steam never opens the first time after millenium install, it'll appear fine on task manager, but it won't popup on taskbar/ taskbar icon section. I have to open task manager everytime to close the service, to try and open again for it to finally work, and even then, it might not work first time. 
Friend of mine suffers from the same thing

### Expected Behavior

I'd expect it to work just like normal steam, before i used the 1.1.5 version which still used the .exe file and was fine...

### Steps To Reproduce

Me and my friend just need to change account or restart the pc / close steam for this bug to happen.

### Operating System

Windows

**Comment by shdwmtr** [comment]
Try the latest version.

**Comment by shdwmtr** [comment]
Closing for no response.
