### ISSUE TITLE
[Feature]Can you put the required packages in the zip file

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#86]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

I hope the required packages can be in the zip file.Because when I share the project with others, it always fails to download the packages or takes too long, resulting in not showing in Settings.
![QQ图片20240825135045](https://github.com/user-attachments/assets/e86a9540-1569-4c4f-b2c2-0964a058bdf8)

**Comment by ShadowMonster99** [comment]
Millennium requires an internet connection on the first setup. It's the only supported way to install. You should install Millennium from this guide: https://docs.steambrew.app/users/installing#automatic

**Comment by YCZ01111** [comment]
> Millennium requires an internet connection on the first setup. It's the only supported way to install. You should install Millennium from this guide: https://docs.steambrew.app/users/installing#automatic

Okay, but there's another issue. After installation, there seems to be a probability that Steamui won't display when it first starts. At this point, it is necessary to open the task manager to end the process of Steam and then open Steam again in order to start it normally

**Comment by ShadowMonster99** [comment]
Take a look at this, whenever that happens. https://docs.steambrew.app/users/trouble-shooting#installed-but-not-showing-in-settings

**Comment by YCZ01111** [comment]
> Take a look at this, whenever that happens. https://docs.steambrew.app/users/trouble-shooting#installed-but-not-showing-in-settings

Has someone experienced this situation, is it a network problem or a computer problem?
![QQ图片20240826185308](https://github.com/user-attachments/assets/58e21dc9-39ec-4940-a07d-bb37d33cfb60)

**Comment by ShadowMonster99** [comment]
It seems to be a network related issue.

**Comment by YCZ01111** [comment]
> It seems to be a network related issue.

I also think so, so I can only package the ext folder and send it to these people for use, although it's not a good solution.

**Comment by shdwmtr** [comment]
Who is "these people"? Is it more than one person having this issue?

**Comment by YCZ01111** [comment]
> Who is "these people"? Is it more than one person having this issue?

I am a video creator who provides theme services for my audience. Most of the people who experience the above situation come from the same region. This should be related to the local network.

**Comment by shdwmtr** [comment]
Whats the specific region?

**Comment by YCZ01111** [comment]
> Whats the specific region?

Most of them come from Jiangsu Province, China

**Comment by shdwmtr** [comment]
Its likely just ISP settings blocking them from accessing clear net stuff considering its China

**Comment by YCZ01111** [comment]
> Its likely just ISP settings blocking them from accessing clear net stuff considering its China

Other regions in China do not encounter such problems

**Comment by shdwmtr** [comment]
For those with the issue, see if they can connect to https://pypi.org/ in their browser. If not, it's an ISP issue

**Comment by YCZ01111** [comment]
> For those with the issue, see if they can connect to https://pypi.org/ in their browser. If not, it's an ISP issue

I tested it with some people, and some people can even connect to  https://pypi.org/ in their browser, but still unable to successfully install Millennium.

**Comment by shdwmtr** [comment]
do all users have the same error message?

**Comment by YCZ01111** [comment]
> do all users have the same error message?

Sorry, I cannot collect too many debugging samples, but they all have issues at PIPX. This situation is still related to China's online environment and cannot be resolved. But they can use VPN for installation. I think this matter can come to an end now. Another issue is that some people encounter situations where their Steam store cannot be opened after installing Millennium. Although game accelerators are required in China to access the Steam store, even with the game accelerator installed after Millennium, these people cannot access the Steam store. Only a portion of people have experienced this situation without any pattern, and I don't know what caused it. And once they uninstall Millennium, they can smoothly access the Steam store.

**Comment by YCZ01111** [comment]
> do all users have the same error message?

Sorry, I am unable to collect too many debugging samples, but these people are experiencing issues at PIPX. This situation is still related to China's online environment and cannot be resolved. But they can use VPN for installation. I think this matter can come to an end now. Another issue is that some people encounter situations where their Steam store cannot be opened after installing Millennium. Although game accelerators are required in China to access the Steam store, even with the game accelerator installed after Millennium, these people cannot access the Steam store. Only a portion of people have experienced this situation without any pattern, and I don't know what caused it. And once they uninstall Millennium, they can smoothly access the Steam store.

**Comment by YCZ01111** [comment]
> do all users have the same error message?

Sorry, I am unable to collect too many debugging samples, but these people are experiencing issues at PIPX. This situation is still related to China's online environment and cannot be resolved. But they can use VPN for installation. I think this matter can come to an end now. Another issue is that some people experience difficulty accessing their Steam store after installing Millennium. Although in China, it is necessary to turn on the game accelerator to access the Steam store, after installing Millennium, these people cannot access the Steam store even if they turn on the game accelerator. Only a portion of people have experienced this situation without any pattern, and I don't know what caused it. And once they uninstall Millennium, they can smoothly access the Steam store.
