### ISSUE TITLE
[Bug]Can I download the required package and package it for someone else

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#88]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

I packaged my ext folder that had already downloaded the required packages and sent it to someone who couldn't download it properly. It seems that they can use it normally. May I ask if there are any drawbacks to doing so and if it will leak my personal data.

### Expected Behavior

I hope to receive a response as soon as possible

### Steps To Reproduce

windows 10 and windows 11

### Operating System

Windows

**Comment by madmaxgrey** [comment]
> ### Before Reporting
> 
>     * [x]  I found no existing issues matching my bug
> 
>     * [x]  My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
> 
>     * [x]  My issue is not caused by a theme
> 
> 
> ### Describe the Bug
> 
> I packaged my ext folder that had already downloaded the required packages and sent it to someone who couldn't download it properly. It seems that they can use it normally. May I ask if there are any drawbacks to doing so and if it will leak my personal data.
> ### Expected Behavior
> 
> I hope to receive a response as soon as possible
> ### Steps To Reproduce
> 
> windows 10 and windows 11
> ### Operating System
> 
> Windows
> ### Anything else?
> 
> _No response_



you can read our faq 
https://docs.steambrew.app/users/faq#is-millennium-against-the-steam-privacy-policy

**Comment by madmaxgrey** [comment]
also if your friend is unable to install please make sure there is no antivirus etc... blocking the installation or steambrew website, if there is, whitelist the steam folder or the steambrew site, isn't the best work around but its the easiest,
also any logs from them installing would actually be very helpful in troubleshooting

**Comment by YCZ01111** [comment]
> also if your friend is unable to install please make sure there is no antivirus etc... blocking the installation or steambrew website, if there is, whitelist the steam folder or the steambrew site, isn't the best work around but its the easiest,
> also any logs from them installing would actually be very helpful in troubleshooting

My friend's computer doesn't have any firewall turned on, perhaps this situation is related to his local network operator. Currently, he has successfully applied the theme using the ext folder I provided. Can I continue to provide ext folders for other friends like this?

**Comment by madmaxgrey** [comment]
its not the best idea because it would be better to troubleshoot the issue instead of just bypassing it,
we would rather you provide the install logs if it fails etc...

**Comment by shdwmtr** [comment]
Closing as there is no more activity and seems to be resolved
