### ISSUE TITLE
Can a switch be added to control the update function?

### ISSUE THREAD

**Issue by YCZ01111** [SteamClientHomebrew/Millennium#95]
### Before Requesting

- [X] I found no existing issue matching my feature request
- [X] This request is related to Millennium, and not a request for a specific theme/addon

### Describe the feature you'd like!

Detecting a Millennium update but failing to update will directly result in the unavailability of Millennium. Can you add a switch to control the update function?

**Comment by shdwmtr** [comment]
In `"C:\Program Files (x86)\Steam\ext\millennium.ini"`, set `check_for_updates` to `no`

**Comment by YCZ01111** [comment]
> In `"C:\Program Files (x86)\Steam\ext\millennium.ini"`, set `check_for_updates` to `no`

Okay, thank you

**Comment by YCZ01111** [comment]
> In , set to `"C:\Program Files (x86)\Steam\ext\millennium.ini"``check_for_updates``no`

Some people may encounter the situation where port 8080 is occupied when check_for_updates is set to no, but in reality, there are no other programs occupying this port.
![UW}27KX0}ECOEBT1JV7IPK4](https://github.com/user-attachments/assets/df26c0b9-0fe0-4627-b53f-a83d7122d666)
![d01f76f19ee68b6067201bb865e7a746](https://github.com/user-attachments/assets/cabc22a7-6529-43bd-8205-87f29f4d1c88)
![82c776143056878eb981427ee1fed336](https://github.com/user-attachments/assets/34dcdb6d-324f-42a6-96aa-52d91965a497)

**Comment by shdwmtr** [comment]
That issue also occurs when some other software/setting is blocking Millennium from making HTTP requests. Could be antivirus, firewall, or device config

**Comment by YCZ01111** [comment]
> That issue also occurs when some other software/setting is blocking Millennium from making HTTP requests. Could be antivirus, firewall, or device config

The firewall and other antivirus software have been turned off. The only variable that triggers this error is check_for_update. When yes, this error will not occur.

**Comment by shdwmtr** [comment]
There must be some other issue at hand, because It isn't Millennium. `check_for_updates` solely exists to block update checking, and nothing else.

Try starting steam with `-devtools-port=9090` to see if the error still appears

**Comment by YCZ01111** [comment]
> There must be some other issue at hand, because It isn't Millennium. `check_for_updates` solely exists to block update checking, and nothing else.
> 
> Try starting steam with `-devtools-port=9090` to see if the error still appears

When set check_for_updates to 'no' and start steam with `-devtools-port=9090`
![1B56567391AE93C6EB95A7DB457112F4](https://github.com/user-attachments/assets/17646097-1459-405c-955b-ef4b4519e695)

**Comment by YCZ01111** [comment]
> There must be some other issue at hand, because It isn't Millennium. solely exists to block update checking, and nothing else.`check_for_updates`
> 
> Try starting steam with to see if the error still appears`-devtools-port=9090`

Just to add, these people will not encounter any errors when starting Steam after setting check_for_updates to yes. But when they switch accounts, there will be an 8080 port error.

**Comment by YCZ01111** [comment]
Multiple instances of port 8080 being occupied due to setting check_for_updates to 'no'. These users will display 'occupied' regardless of the port they set.
