### ISSUE TITLE
[Bug] Skin not applying after exiting BPM

### ISSUE THREAD

**Issue by ExclusiveBum** [SteamClientHomebrew/Millennium#96]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

After getting out of big picture mode theme reverses to the original one

### Expected Behavior

It should stay always the theme i picked.

### Steps To Reproduce

1. Open steam. 
3. Go to big picture mode. 
3. Get out of big picture mode. 
5. See the original theme of steam.

### Operating System

Windows

**Comment by shdwmtr** [comment]
Fix in the latest version.
