### ISSUE TITLE
[Bug] "Millennium can't connect...target port '8080' is being used by ' '."

### ISSUE THREAD

**Issue by antitheus185** [SteamClientHomebrew/Millennium#98]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

Bug begins with Millennium first being unable to find something at this link: https://steamloopback.host/appdetails/achievement_progress.json 
![image](https://github.com/user-attachments/assets/1364313e-9062-4e8b-9b3e-0837c29bab2f)
Then at the end of the console in DevTools, there's a lot of connection refused errors - all having to do with source maps and being unable to load them. 
![image](https://github.com/user-attachments/assets/024cf32d-eacb-47a3-a7e0-7ff8607ac66c)
And the issue is presented with an error pop-up telling me port 8080 is occupied by another process. The only process running on port 8080 when I check in Powershell is steamwebhelper.exe. 
![image](https://github.com/user-attachments/assets/4660ac33-371a-49f9-8285-06e3963db84a)

### Expected Behavior

Not really sure, never used this before so I don't know how it should work.

### Steps To Reproduce

Follow instructions provided with latest version on Windows 10.
Run steam.exe.

### Operating System

Windows

### Anything else?

[devtools-log.log](https://github.com/user-attachments/files/16861667/devtools-log.log)

**Comment by antitheus185** [comment]
I forgot to mention this in the issue above, but Steam seems to operate normally as long as I do not interact with the pop-up in any way (clicking "OK" or closing it), but I assume it's just vanilla Steam as Millennium couldn't load correctly. Once I interact with the pop-up though, it shuts it down immediately. Not sure if this is helpful in any way for this, just figured I should mention it anyway.

**Comment by shdwmtr** [comment]
This is usually a problem with an antivirus, firewall, or system settings, or even steam settings.

**Comment by shdwmtr** [comment]
https://github.com/SteamClientHomebrew/Millennium/issues/26

Some found success disabling hardware acceleration

**Comment by Linx-ESP** [comment]
```
[15:55.836] WARN Millennium can't connect to Steam because the target port '8080' is currently being used by 'C:\Program Files (x86)\Steam\steamapps\common\Wildlands\GRW.exe'.
To address this you must uninstall/close the conflicting app, change the port it uses (assuming its possible), or uninstall Millennium.
```

This happens with Ghost Recon Wildlands too

**Comment by shdwmtr** [comment]
@Linx-ESP in your case, it seems Ghost Recon needs port 8080, while steam also needs it at the same time. To fix that you'll have to change steam's launch args, and add `-devtools-port=some-other-port`, and launch steam from a separate shortcut then normal. There is nothing I can do about unless you can change the port GRW listens on, because you can't change the one steam is on.

**Comment by antitheus185** [comment]
> This is usually a problem with an antivirus, firewall, or system settings, or even steam settings.


> #26
> 
> Some found success disabling hardware acceleration

Ah, good to know. I usually remove Windows Defender when I install Windows to my PC but I didn't this time, gonna do that in a moment to see if it fixes it. If it doesn't, then I'll disable hardware acceleration.

**Comment by shdwmtr** [comment]
Those source map errors and 404's are nothing of concern. It should be working perfectly!

**Comment by antitheus185** [comment]
Thank you, and it is working perfectly — I've already loaded the Metro skin so far and it's having zero issues. I'm still not sure what caused the bug, and since there's no more issues and the other errors are not related to it, I'll be closing the issue. Thank you again!

**Comment by MMK-2004** [comment]
@shdwmtr that actually helped thanks

**Comment by boyikao** [comment]
So how should this problem be solved?

**Comment by antitheus185** [comment]
> So how should this problem be solved?

Reboot your pc, oddly enough this seems to be necessary. If that doesn't work, then try and see if anything's occupying the port Millenium is needing.

**Comment by BenFuller321** [comment]
I've just gottent this issue and apparently it is because qbittorrent is using port 8080

**Comment by MatheusPalhares** [comment]
This happened to me but i was really using port 8080 for hosting another application on my pc and i don't want to kill it just to open steam

Can't i just change the port Millenium use?

**Comment by ejalxndr** [comment]
No, it has been fixed in the alpha version of Millennium though. If you use it you need to be on Steam beta.
